{
  self,
  inputs,
}: {
  config,
  pkgs,
  lib,
  ...
}: let
  inherit (lib.modules) mkIf;
  inherit (lib.strings) hasInfix;
  inherit (lib.generators) toINI;

  cfg = config.programs.schizofox;

  schizofoxPkgs =
    if pkgs ? mkSchizofox
    then pkgs
    else pkgs.extend self.overlays.default;
  schizofox = schizofoxPkgs.mkSchizofox (
    (self.lib.schizofoxArgsFromModule {
      inherit cfg lib;
      pkgs = schizofoxPkgs;
    })
    // {
      firefox-unwrapped = cfg.package;
      prefName = cfg.prefName;
      wrapFirefox = cfg.wrapFirefox;
      wrapperArgs = cfg.wrapperArgs;
      nixpakLib = inputs.nixpak.lib.nixpak {
        inherit (schizofoxPkgs) lib;
        pkgs = schizofoxPkgs;
      };
    }
  );
  # the raw systemd user unit generated by the wrapper; `systemd.user.units'
  # expects a text representation instead of raw [Unit]/[Install]/[Service]
  # sections.
  searxRandomizerUnit = schizofox.searx-randomizer-unit;
in {
  meta.maintainers = with lib.maintainers; [NotAShelf];
  imports = [self.lib.schizofoxOptions];
  config = mkIf cfg.enable {
    environment.systemPackages = [schizofox.package];
    systemd.user.units."searx-randomizer.service" = mkIf cfg.search.searxRandomizer.enable {
      enable = true;
      wantedBy = searxRandomizerUnit.Install.WantedBy;
      text =
        toINI {
          mkKeyValue = pkgs.lib.generators.mkKeyValueDefault {
            mkValueString = v:
              if builtins.isList v
              then lib.concatStringsSep " " (map toString v)
              else toString v;
          } "=";
        }
        searxRandomizerUnit;
    };

    assertions = [
      {
        assertion = hasInfix "esr" cfg.package.version;
        message = ''
          The package provided to 'programs.schizofox.package' is not an ESR release
          of Firefox: ${cfg.package.pname}

          For policies to function as intended, you must an ESR release of Firefox.
          If you think this is a mistake, please open an issue and let us know.
        '';
      }
    ];
  };
}
