{
  self,
  inputs,
}: {
  config,
  pkgs,
  lib,
  ...
}: let
  inherit (lib.modules) mkIf;
  inherit (lib.strings) hasInfix;
  inherit (lib.generators) toINI;

  cfg = config.programs.schizofox;

  schizofox = (pkgs.callPackage self.lib.mkSchizofox {}) (
    (import ../../pkgs/schizofox/from-module.nix {inherit cfg pkgs lib;})
    // {
      firefox-unwrapped = cfg.package;
      nixpakLib = inputs.nixpak.lib.nixpak {
        inherit (pkgs) lib;
        inherit pkgs;
      };
    }
  );

  # the raw systemd user unit generated by the wrapper; `systemd.user.units'
  # expects a text representation instead of raw [Unit]/[Install]/[Service]
  # sections.
  searxRandomizerUnit = schizofox.searx-randomizer-unit;
in {
  meta.maintainers = with lib.maintainers; [NotAShelf];
  imports = [self.lib.schizofoxOptions];
  config = mkIf cfg.enable {
    environment.systemPackages = [schizofox.package];
    systemd.user.units.searx-randomizer = mkIf cfg.search.searxRandomizer.enable {
      enable = true;
      wantedBy = searxRandomizerUnit.Install.WantedBy;
      text =
        toINI {
          mkKeyValue = pkgs.lib.generators.mkKeyValueDefault {
            mkValueString = v:
              if builtins.isList v
              then lib.concatStringsSep " " (map toString v)
              else toString v;
          } "=";
        }
        searxRandomizerUnit;
    };

    assertions = [
      {
        assertion = hasInfix "esr" cfg.package.version;
        message = ''
          The package provided to 'programs.schizofox.package' is not an ESR release
          of Firefox: ${cfg.package.pname}

          For policies to function as intended, you must an ESR release of Firefox.
          If you think this is a mistake, please open an issue and let us know.
        '';
      }
    ];
  };
}
