.Dd January 1, 1980
.Dt schizofox 1
.Os schizofox
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" enable line breaks after slashes
.cflags 4 /
.Sh NAME
.Nm schizofox
.Nd a hardened Firefox build for the delusional and schizophrenic
.
.Sh BUGS
.Pp
Please report any bugs on the
\m[blue]\fBproject issue tracker\fR\m[]\&.

.Sh AUTHOR
.Pp
\fBschizofox contributors\fR
.RS 4
Author.
.RE

.Sh COPYRIGHT
.br
Copyright \(co 2022\(en2023 schizofox contributors
.br
