{
  preferences,
  chrome,
  sandbox,
  searchService,
  lib,
  pkgs,
  prefName ? "pref",
  nixpakLib ? null,
  cursorTheme ? null,
  iconTheme ? null,
  gtkTheme ? null,
  wrappedPackage,
  ...
}: let
  inherit (builtins) toJSON isBool isInt isString;
  inherit (lib.strings) concatStrings;
  inherit (lib.attrsets) mapAttrsToList;
  inherit (lib.lists) optionals optional;

  userPrefValue = pref:
    toJSON (
      if isBool pref || isInt pref || isString pref
      then pref
      else toJSON pref
    );

  # A user sheet is registered at startup for every profile, including profiles
  # created after the wrapper was built. Browser-only CSS must not style websites.
  css = pkgs.writeText "schizofox.css" ''
    @-moz-document url-prefix("chrome://") {
      ${chrome.userChrome}
    }

    ${chrome.userContent}
  '';

  autoconfig = ''
    // Generated by Schizofox; runs in the Firefox Autoconfig context.
    ${lib.optionalString (chrome.userChrome != "" || chrome.userContent != "") ''
      const {classes: Cc, interfaces: Ci} = Components;
      const styleSheetService = Cc["@mozilla.org/content/style-sheet-service;1"]
        .getService(Ci.nsIStyleSheetService);
      const stylesheet = Services.io.newURI("file://${css}");
      styleSheetService.loadAndRegisterSheet(stylesheet, Ci.nsIStyleSheetService.USER_SHEET);
    ''}

    ${concatStrings (
      mapAttrsToList (name: value: ''
        ${prefName}(${toJSON name}, ${userPrefValue value});
      '')
      preferences
    )}
  '';

  just' = v: lib.optional (v != null);
  just = v: just' v v;

  searx-randomizer-unit = {
    Unit = {
      Description = "Searx instance randomizer";
      Documentation = "https://github.com/schizofox/searx-randomizer";
    };

    Install.WantedBy = ["graphical-session.target"];

    Service = {
      Environment = let
        engines = toJSON searchService.instances;
      in ["SEARX_INSTANCES=${pkgs.writeText "engines.json" engines}"];
      ExecStart = "${pkgs.schizofox-searx-randomizer}/bin/searx-randomizer";
      Restart = "always";
      RestartSec = 12;
    };
  };

  package =
    if nixpakLib != null && sandbox.enable
    then
      (nixpakLib {
        config = {sloth, ...}: let
          appId = "org.mozilla.Firefox";
        in {
          flatpak = {inherit appId;};
          app.package = wrappedPackage;
          app.binPath = "bin/schizofox";

          dbus.policies = {
            "${appId}" = "own";
            "${appId}.*" = "own";
            "org.a11y.Bus" = "talk";
            "org.gnome.SessionManager" = "talk";
            "org.freedesktop.ScreenSaver" = "talk";
            "org.gtk.vfs.*" = "talk";
            "org.gtk.vfs" = "talk";
            "org.freedesktop.Notifications" = "talk";
            "org.freedesktop.portal.FileChooser" = "talk";
            "org.freedesktop.portal.Settings" = "talk";
            "org.mpris.MediaPlayer2.firefox.*" = "own";
            "org.mozilla.firefox.*" = "own";
            "org.mozilla.firefox_beta.*" = "own";
            "org.freedesktop.DBus" = "talk";
            "org.freedesktop.DBus.*" = "talk";
            "ca.desrt.dconf" = "talk";
            "org.freedesktop.portal.*" = "talk";
            "org.freedesktop.NetworkManager" = "talk";
            "org.freedesktop.FileManager1" = "talk";
          };

          gpu.enable = true;
          gpu.provider = "bundle";
          fonts.enable = true;
          locale.enable = true;
          etc.sslCertificates.enable = true;

          bubblewrap = let
            envSuffix = envKey: sloth.concat' (sloth.env envKey);
          in {
            network = true;

            bind.rw =
              [
                (sloth.concat' sloth.xdgCacheHome "/fontconfig")
                (sloth.concat' sloth.xdgCacheHome "/mesa_shader_cache")
                (sloth.concat [
                  (sloth.env "XDG_RUNTIME_DIR")
                  "/"
                  (sloth.envOr "WAYLAND_DISPLAY" "no")
                ])
                "/tmp/.X11-unix"
                (sloth.envOr "XAUTHORITY" "/no-xauth")
                (envSuffix "XDG_RUNTIME_DIR" "/at-spi/bus")
                (envSuffix "XDG_RUNTIME_DIR" "/gvfsd")
                (envSuffix "XDG_RUNTIME_DIR" "/pulse")
                (envSuffix "XDG_RUNTIME_DIR" "/doc")
                (envSuffix "XDG_RUNTIME_DIR" "/dconf")
              ]
              ++ (optional (!sandbox.customMozillaFolder.enable) (sloth.concat' sloth.homeDir "/.mozilla"))
              ++ (optionals sandbox.customMozillaFolder.enable [
                (sloth.concat' sloth.homeDir sandbox.customMozillaFolder.path)
                (sloth.concat' sloth.homeDir "/.mozilla")
              ]);

            bind.ro = builtins.concatLists [
              [
                "/etc/resolv.conf"
                (sloth.concat' sloth.xdgConfigHome "/gtk-2.0")
                (sloth.concat' sloth.xdgConfigHome "/gtk-3.0")
                (sloth.concat' sloth.xdgConfigHome "/gtk-4.0")
                (sloth.concat' sloth.xdgConfigHome "/dconf")
                "/etc/localtime"
                "/sys/bus/pci"
                [
                  "${wrappedPackage}/lib/firefox"
                  "/app/etc/firefox"
                ]
              ]
              (just' cursorTheme "${cursorTheme}")
              sandbox.extraBinds
              (optionals sandbox.allowFontPaths ["/etc/fonts"])
            ];

            env = {
              XDG_DATA_DIRS = lib.makeSearchPath "share" (
                [pkgs.shared-mime-info]
                ++ just iconTheme
                ++ just gtkTheme
                ++ just cursorTheme
              );
              XCURSOR_PATH = lib.mkIf (cursorTheme != null) (
                lib.concatStringsSep ":" [
                  "${cursorTheme}/share/icons"
                  "${cursorTheme}/share/pixmaps"
                ]
              );
            };
          };
        };
      })
      .config
      .env
    else wrappedPackage;
in
  assert lib.assertMsg (builtins.elem prefName ["pref" "lockPref"]) "mkSchizofox.prefName must be pref or lockPref"; {
    inherit autoconfig package searx-randomizer-unit;
  }
