name: Checks
on: [push, pull_request, workflow_dispatch, workflow_call]
env:
  GH_TOKEN: ${{ github.token }}

jobs:
  check:
    strategy:
      matrix:
        command:
          - nix flake check --accept-flake-config
          - nix run nixpkgs#alejandra -- -c .

    uses: ./.github/workflows/nix.yml
    with:
      command: ${{ matrix.command }}
    secrets:
      GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
