name: Deploy documentation

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/docs.yml
      - docs/**
      - flake/docs/**
      - flake/lib/schizofox/options/**
      - flake.nix
      - flake.lock
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Build documentation
        run: nix build .#docs --accept-flake-config

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: result

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
